#!/bin/bash

#!/bin/sh
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2016 Thomas Lübking, https://github.com/luebking/nodesk
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this script, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.
#

# A calendar.
# Parameter $1 is seconds to autoclose (default: "" ie. never)
# Parameter $2 "toggle" indicates a singleton

# Requires:
# 1. dzen2
# 2. cal ;-)

FONT="Noto Mono-12" # use a monospaced font, Noto doesn't slash "0" ;-)
COLOR_FG='#272727'
COLOR_BG='#FAFAFA'
COLOR_FG_WEEK='#BBBBBB'
COLOR_FG_NOW='#1793D0'
LOCK_FILE=/tmp/.$USER.xcal

######## hands off #############

if [ "$2" = "toggle" -a -e "$LOCK_FILE" ]; then
    read PID < "$LOCK_FILE"
    rm "$LOCK_FILE" > /dev/null 2>&1
    if kill $PID > /dev/null 2>&1; then
        exit
    fi
fi

PAGE=`cal -mw --color=always | sed 's/\x1b\[7m/^fg('$COLOR_FG_NOW')/g; s/\x1b\[27m/^fg()/g; /^\s*$/d'`
HEADER='^fg('$COLOR_FG_NOW')'`head -n1 <<< "$PAGE"`'^fg()'
MONTH=`sed '1d; s/^\([^ ]\+\) /^fg('$COLOR_FG_WEEK')\1^fg() /g; s/^\(.*\)$/^fg('$COLOR_FG_WEEK')\1^fg()/' <<< "$PAGE"`

WIDTH=$((9*23 + 16)) # 9 as font factor, 23 chars, 2*8px padding


dzen2 -p $1 -e 'onstart=uncollapse,unhide;button1=exit:1' \
      -y 32 -x -${WIDTH} -sa c -l `wc -l <<< "$MONTH"` -w $WIDTH -fn "$FONT" \
      -bg "$COLOR_BG" -fg "$COLOR_FG" < <(echo "$HEADER"; echo "$MONTH") &

if [ "$2" = "toggle" ]; then
    echo $! > "$LOCK_FILE"
    wait $! > /dev/null 2>&1
    rm "$LOCK_FILE" > /dev/null 2>&1
fi